export const PERSONA_CONFIG = {
  baker: {
    tabLabel:          'Orders',
    heroCtaTarget:     '#menu',
    servicesLabel:     'Our Menu',
    bioLabel:          'Our Story',
    highlightsLabel:   'Why Choose Us',
    contactLabel:      'General Enquiries',
    contactVariant:    'enquiry' as const,
    serviceCardAction: 'order'  as const,
    orderLabel:        'Order',
    hasQuantity:       true,
    hasNotes:          true,
    hasCustomOrder:    true,
    leadTimeNotice:    'Custom orders need at least 2–3 days notice',
  },
  chef: {
    tabLabel:          'Enquiries',
    heroCtaTarget:     '#menu',
    servicesLabel:     'Our Menu & Plans',
    bioLabel:          'About the Chef',
    highlightsLabel:   'Our Specialties',
    contactLabel:      'Get in Touch',
    contactVariant:    'enquiry' as const,
    serviceCardAction: 'order'  as const,
    orderLabel:        'Enquire',
    hasQuantity:       false,
    hasNotes:          true,
    hasCustomOrder:    true,
    leadTimeNotice:    null,
  },
  sellganeshidols: {
    tabLabel:          'Enquiries',
    // Unread by HeroPdp itself (this persona's only hero variant — it uses
    // primaryCtaLabel/openOrder instead), but kept correct rather than
    // removed: PERSONA_CONFIG's shape is shared across all 46 personas and
    // other callers (ServiceCTA, non-pdp hero variants) do read it.
    heroCtaTarget:     '#idols',
    servicesLabel:     'More from the Heritage Collection',
    bioLabel:          'About Us',
    highlightsLabel:   'Why Choose Us',
    contactLabel:      'Enquire / Order',
    contactVariant:    'enquiry' as const,
    serviceCardAction: 'order'  as const,
    orderLabel:        'Enquire',
    hasQuantity:       false,
    hasNotes:          true,
    hasCustomOrder:    true,
    leadTimeNotice:    'Advance orders recommended, especially before Ganesh Chaturthi',
    // Matches the approved mockup's hero eyebrow exactly — a static
    // per-persona phrase, not the member's name, so it doesn't reintroduce
    // the banned name-eyebrow pattern (see HeroSection.test.tsx).
    heroEyebrow:       'Handcrafted for Ganesh Chaturthi',
    // Ganesh-only ghost/outline enquire-button style, matching the mockup
    // exactly (see ServicesSection.tsx's Collection variant) — belongs in
    // config per the no-hardcoding convention, not an
    // if(persona==='sellganeshidols') branch in the component.
    orderButtonStyle:  'ghost' as const,
    // v3 rebuild (designscreenshots/sellganeshidolsv3.pdf) — the hero is now
    // a two-column product-detail layout, not a flat full-bleed field. These
    // fields are Ganesh-only, same 'x' in cfg narrowing pattern as
    // heroEyebrow/orderButtonStyle above.
    navLabel:          'Sell Ganesh Idols',
    // '#idols' — the FactsSection idol-showcase grid (v3.1 rebuild); was
    // '#menu', the now-unused Collection grid, which no longer renders for
    // this persona (see inngest/build-page.ts PERSONA_SECTIONS).
    navLinks: [
      { label: 'Collections',    target: '#idols' },
      { label: 'Custom Orders',  target: '#custom' },
      { label: 'Materials',      target: '#materials' },
    ],
    sizeSelectorLabel: 'Select size',
    includesLabel:     'Includes',
    primaryCtaLabel:   'Reserve This Piece',
    secondaryCtaLabel: 'Request Custom Size or Finish',
    festivePriceLabel: 'Festive Price',
  },
  salon: {
    tabLabel:          'Appointments',
    heroCtaTarget:     '#book',
    servicesLabel:     'Services & Pricing',
    bioLabel:          'About Us',
    highlightsLabel:   'Why Choose Us',
    contactLabel:      'Book an Appointment',
    contactVariant:    'both' as const,
    serviceCardAction: 'book' as const,
    orderLabel:        'Book',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
  doctor: {
    tabLabel:          'Appointments',
    heroCtaTarget:     '#book',
    servicesLabel:     'Consultations & Treatments',
    bioLabel:          'About Dr.',
    highlightsLabel:   'Our Approach',
    contactLabel:      'Book a Consultation',
    contactVariant:    'both' as const,
    serviceCardAction: 'book' as const,
    orderLabel:        'Book',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
  tutor: {
    tabLabel:          'Sessions',
    heroCtaTarget:     '#book',
    servicesLabel:     'Programs',
    bioLabel:          'Meet Your Tutor',
    highlightsLabel:   'Why Learn With Me',
    contactLabel:      'Book a Free Demo Class',
    contactVariant:    'both' as const,
    serviceCardAction: 'book' as const,
    orderLabel:        'Book Demo',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
  trainer: {
    tabLabel:          'Sessions',
    heroCtaTarget:     '#book',
    servicesLabel:     'Training Programs',
    bioLabel:          'My Journey',
    highlightsLabel:   'Why Train With Me',
    contactLabel:      'Book a Free Consultation',
    contactVariant:    'both' as const,
    serviceCardAction: 'book' as const,
    orderLabel:        'Enquire',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
  photographer: {
    tabLabel:          'Enquiries',
    heroCtaTarget:     '#portfolio',
    servicesLabel:     'Packages',
    bioLabel:          'My Story',
    highlightsLabel:   'My Style',
    contactLabel:      'Check My Availability',
    contactVariant:    'both' as const,
    serviceCardAction: 'book' as const,
    orderLabel:        'Enquire',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
  musician: {
    tabLabel:          'Enquiries',
    heroCtaTarget:     '#book',
    servicesLabel:     'I Perform At',
    bioLabel:          'About Me',
    highlightsLabel:   'Why Hire Me',
    contactLabel:      'Book Me for Your Event',
    contactVariant:    'both' as const,
    serviceCardAction: 'enquire' as const,
    orderLabel:        'Enquire',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
  advocate: {
    tabLabel:          'Consultations',
    heroCtaTarget:     '#book',
    servicesLabel:     'Practice Areas',
    bioLabel:          'About the Advocate',
    highlightsLabel:   'Why Work With Me',
    contactLabel:      'Book a Consultation',
    contactVariant:    'both' as const,
    serviceCardAction: 'book' as const,
    orderLabel:        'Book Consultation',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
  physio: {
    tabLabel:          'Appointments',
    heroCtaTarget:     '#book',
    servicesLabel:     'Treatments & Services',
    bioLabel:          'About the Physiotherapist',
    highlightsLabel:   'Our Approach',
    contactLabel:      'Book an Appointment',
    contactVariant:    'both' as const,
    serviceCardAction: 'book' as const,
    orderLabel:        'Book',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
  occtherapist: {
    tabLabel:          'Appointments',
    heroCtaTarget:     '#book',
    servicesLabel:     'Occupational Therapy Services',
    bioLabel:          'About the Occupational Therapist',
    highlightsLabel:   'Our Approach',
    contactLabel:      'Book a Session',
    contactVariant:    'both' as const,
    serviceCardAction: 'book' as const,
    orderLabel:        'Book',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
  speech: {
    tabLabel:          'Appointments',
    heroCtaTarget:     '#book',
    servicesLabel:     'Speech & Language Services',
    bioLabel:          'About the Speech Therapist',
    highlightsLabel:   'Our Approach',
    contactLabel:      'Book a Session',
    contactVariant:    'both' as const,
    serviceCardAction: 'book' as const,
    orderLabel:        'Book',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
  chiro: {
    tabLabel:          'Appointments',
    heroCtaTarget:     '#book',
    servicesLabel:     'Chiropractic / Osteopathic Services',
    bioLabel:          'About the Practitioner',
    highlightsLabel:   'Our Approach',
    contactLabel:      'Book an Appointment',
    contactVariant:    'both' as const,
    serviceCardAction: 'book' as const,
    orderLabel:        'Book',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
  counselor: {
    tabLabel:          'Sessions',
    heroCtaTarget:     '#book',
    servicesLabel:     'Therapy & Counselling Services',
    bioLabel:          'About the Therapist',
    highlightsLabel:   'My Approach',
    contactLabel:      'Book a Free Consultation',
    contactVariant:    'both' as const,
    serviceCardAction: 'book' as const,
    orderLabel:        'Book',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
  homeopath: {
    tabLabel:          'Appointments',
    heroCtaTarget:     '#book',
    servicesLabel:     'Homoeopathic Services',
    bioLabel:          'About the Homoeopath',
    highlightsLabel:   'Our Philosophy',
    contactLabel:      'Book a Consultation',
    contactVariant:    'both' as const,
    serviceCardAction: 'book' as const,
    orderLabel:        'Book',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
  ayurveda: {
    tabLabel:          'Appointments',
    heroCtaTarget:     '#book',
    servicesLabel:     'Ayurvedic Services',
    bioLabel:          'About the Ayurvedic Practitioner',
    highlightsLabel:   'Our Philosophy',
    contactLabel:      'Book a Consultation',
    contactVariant:    'both' as const,
    serviceCardAction: 'book' as const,
    orderLabel:        'Book',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
  homenurse: {
    tabLabel:          'Care Schedule',
    heroCtaTarget:     '#book',
    servicesLabel:     'Home Nursing & Care Services',
    bioLabel:          'About the Nurse / Caregiver',
    highlightsLabel:   'Our Commitment',
    contactLabel:      'Enquire About Care',
    contactVariant:    'both' as const,
    serviceCardAction: 'book' as const,
    orderLabel:        'Enquire',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
  postnatal: {
    tabLabel:          'Appointments',
    heroCtaTarget:     '#book',
    servicesLabel:     'Postnatal Care Services',
    bioLabel:          'About the Postnatal Specialist',
    highlightsLabel:   'Our Approach',
    contactLabel:      'Book Postnatal Support',
    contactVariant:    'both' as const,
    serviceCardAction: 'book' as const,
    orderLabel:        'Book',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
  lactation: {
    tabLabel:          'Appointments',
    heroCtaTarget:     '#book',
    servicesLabel:     'Lactation Consulting Services',
    bioLabel:          'About the Lactation Consultant',
    highlightsLabel:   'My Approach',
    contactLabel:      'Book a Consultation',
    contactVariant:    'both' as const,
    serviceCardAction: 'book' as const,
    orderLabel:        'Book',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
  other: {
    tabLabel:          'Inquiries',
    heroCtaTarget:     '#book',
    servicesLabel:     'What I Offer',
    bioLabel:          'About Me',
    highlightsLabel:   'Why Choose Me',
    contactLabel:      'Get in Touch',
    contactVariant:    'both' as const,
    serviceCardAction: 'none' as const,
    orderLabel:        'Get in Touch',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
  // ── Distributor personas ───────────────────────────────────────────────────
  fmcgdist: {
    tabLabel: 'Supply', heroCtaTarget: '#products', servicesLabel: 'Product Lines',
    bioLabel: 'About Us', highlightsLabel: 'Why Deal With Us', contactLabel: 'Trade Enquiries',
    contactVariant: 'enquiry' as const, serviceCardAction: 'enquire' as const,
    orderLabel: 'Enquire', hasQuantity: false, hasNotes: false, hasCustomOrder: false, leadTimeNotice: null,
  },
  pharmadist: {
    tabLabel: 'Supply', heroCtaTarget: '#products', servicesLabel: 'Product Range',
    bioLabel: 'About Us', highlightsLabel: 'Why Supply With Us', contactLabel: 'Supply Enquiries',
    contactVariant: 'enquiry' as const, serviceCardAction: 'enquire' as const,
    orderLabel: 'Enquire', hasQuantity: false, hasNotes: false, hasCustomOrder: false, leadTimeNotice: null,
  },
  electronicsdist: {
    tabLabel: 'Supply', heroCtaTarget: '#brands', servicesLabel: 'Brands & Categories',
    bioLabel: 'About Us', highlightsLabel: 'Why Deal With Us', contactLabel: 'Dealer Enquiries',
    contactVariant: 'enquiry' as const, serviceCardAction: 'enquire' as const,
    orderLabel: 'Enquire', hasQuantity: false, hasNotes: false, hasCustomOrder: false, leadTimeNotice: null,
  },
  autopartsdist: {
    tabLabel: 'Supply', heroCtaTarget: '#parts', servicesLabel: 'Parts Categories',
    bioLabel: 'About Us', highlightsLabel: 'Why Supply With Us', contactLabel: 'Workshop Enquiries',
    contactVariant: 'enquiry' as const, serviceCardAction: 'enquire' as const,
    orderLabel: 'Enquire', hasQuantity: false, hasNotes: false, hasCustomOrder: false, leadTimeNotice: null,
  },
  buildingdist: {
    tabLabel: 'Supply', heroCtaTarget: '#materials', servicesLabel: 'Material Lines',
    bioLabel: 'About Us', highlightsLabel: 'Why Supply With Us', contactLabel: 'Trade Enquiries',
    contactVariant: 'enquiry' as const, serviceCardAction: 'enquire' as const,
    orderLabel: 'Enquire', hasQuantity: false, hasNotes: false, hasCustomOrder: false, leadTimeNotice: null,
  },
  agridist: {
    tabLabel: 'Supply', heroCtaTarget: '#products', servicesLabel: 'Product Categories',
    bioLabel: 'About Us', highlightsLabel: 'Why Deal With Us', contactLabel: 'Dealer Enquiries',
    contactVariant: 'enquiry' as const, serviceCardAction: 'enquire' as const,
    orderLabel: 'Enquire', hasQuantity: false, hasNotes: false, hasCustomOrder: false, leadTimeNotice: null,
  },
  distributor: {
    tabLabel: 'Supply', heroCtaTarget: '#products', servicesLabel: 'Product Lines',
    bioLabel: 'About Us', highlightsLabel: 'Why Deal With Us', contactLabel: 'Trade Enquiries',
    contactVariant: 'enquiry' as const, serviceCardAction: 'enquire' as const,
    orderLabel: 'Enquire', hasQuantity: false, hasNotes: false, hasCustomOrder: false, leadTimeNotice: null,
  },
  // ── Agency personas ────────────────────────────────────────────────────────
  travel: {
    tabLabel: 'Bookings', heroCtaTarget: '#packages', servicesLabel: 'Tour Packages',
    bioLabel: 'About Us', highlightsLabel: 'Why Travel With Us', contactLabel: 'Enquire / Book',
    contactVariant: 'both' as const, serviceCardAction: 'book' as const,
    orderLabel: 'Enquire', hasQuantity: false, hasNotes: true, hasCustomOrder: false, leadTimeNotice: null,
  },
  realestate: {
    tabLabel: 'Enquiries', heroCtaTarget: '#properties', servicesLabel: 'Properties & Services',
    bioLabel: 'About Us', highlightsLabel: 'Why Work With Us', contactLabel: 'Enquire About a Property',
    contactVariant: 'both' as const, serviceCardAction: 'enquire' as const,
    orderLabel: 'Enquire', hasQuantity: false, hasNotes: true, hasCustomOrder: false, leadTimeNotice: null,
  },
  insurance: {
    tabLabel: 'Enquiries', heroCtaTarget: '#services', servicesLabel: 'Insurance Products',
    bioLabel: 'About Me', highlightsLabel: 'Why Choose Us', contactLabel: 'Get in Touch',
    contactVariant: 'both' as const, serviceCardAction: 'enquire' as const,
    orderLabel: 'Enquire', hasQuantity: false, hasNotes: false, hasCustomOrder: false, leadTimeNotice: null,
  },
  staffing: {
    tabLabel: 'Mandates', heroCtaTarget: '#services', servicesLabel: 'Staffing Services',
    bioLabel: 'About Us', highlightsLabel: 'Why Partner With Us', contactLabel: 'Discuss a Requirement',
    contactVariant: 'both' as const, serviceCardAction: 'enquire' as const,
    orderLabel: 'Enquire', hasQuantity: false, hasNotes: false, hasCustomOrder: false, leadTimeNotice: null,
  },
  marketing: {
    tabLabel: 'Enquiries', heroCtaTarget: '#services', servicesLabel: 'Services & Packages',
    bioLabel: 'About Us', highlightsLabel: 'Why Work With Us', contactLabel: 'Request a Proposal',
    contactVariant: 'both' as const, serviceCardAction: 'enquire' as const,
    orderLabel: 'Enquire', hasQuantity: false, hasNotes: false, hasCustomOrder: false, leadTimeNotice: null,
  },
  immigration: {
    tabLabel: 'Consultations', heroCtaTarget: '#services', servicesLabel: 'Services & Pathways',
    bioLabel: 'About Us', highlightsLabel: 'Why Choose Us', contactLabel: 'Book a Consultation',
    contactVariant: 'both' as const, serviceCardAction: 'book' as const,
    orderLabel: 'Book', hasQuantity: false, hasNotes: false, hasCustomOrder: false, leadTimeNotice: null,
  },
  events: {
    tabLabel: 'Enquiries', heroCtaTarget: '#events', servicesLabel: 'Events & Services',
    bioLabel: 'About Us', highlightsLabel: 'Why Choose Us', contactLabel: 'Request a Quote',
    contactVariant: 'both' as const, serviceCardAction: 'enquire' as const,
    orderLabel: 'Enquire', hasQuantity: false, hasNotes: true, hasCustomOrder: false, leadTimeNotice: null,
  },
  logistics: {
    tabLabel: 'Enquiries', heroCtaTarget: '#services', servicesLabel: 'Freight Services',
    bioLabel: 'About Us', highlightsLabel: 'Why Ship With Us', contactLabel: 'Request a Freight Quote',
    contactVariant: 'both' as const, serviceCardAction: 'enquire' as const,
    orderLabel: 'Enquire', hasQuantity: false, hasNotes: true, hasCustomOrder: false, leadTimeNotice: null,
  },
  agency: {
    tabLabel: 'Enquiries', heroCtaTarget: '#services', servicesLabel: 'Services',
    bioLabel: 'About Us', highlightsLabel: 'Why Choose Us', contactLabel: 'Get in Touch',
    contactVariant: 'both' as const, serviceCardAction: 'enquire' as const,
    orderLabel: 'Enquire', hasQuantity: false, hasNotes: false, hasCustomOrder: false, leadTimeNotice: null,
  },
} as const

export type PersonaKey = keyof typeof PERSONA_CONFIG

export function getPersonaConfig(persona: string) {
  return PERSONA_CONFIG[(persona as PersonaKey)] ?? PERSONA_CONFIG.other
}

