export const PERSONA_CONFIG = {
  baker: {
    tabLabel:          'Orders',
    heroCtaTarget:     '#menu',
    servicesLabel:     'Our Menu',
    bioLabel:          'Our Story',
    highlightsLabel:   'Why Choose Us',
    contactLabel:      'General Enquiries',
    contactVariant:    'enquiry' as const,
    serviceCardAction: 'order'  as const,
    orderLabel:        'Order',
    hasQuantity:       true,
    hasNotes:          true,
    hasCustomOrder:    true,
    leadTimeNotice:    'Custom orders need at least 2–3 days notice',
  },
  chef: {
    tabLabel:          'Enquiries',
    heroCtaTarget:     '#menu',
    servicesLabel:     'Our Menu & Plans',
    bioLabel:          'About the Chef',
    highlightsLabel:   'Our Specialties',
    contactLabel:      'Get in Touch',
    contactVariant:    'enquiry' as const,
    serviceCardAction: 'order'  as const,
    orderLabel:        'Enquire',
    hasQuantity:       false,
    hasNotes:          true,
    hasCustomOrder:    true,
    leadTimeNotice:    null,
  },
  salon: {
    tabLabel:          'Appointments',
    heroCtaTarget:     '#book',
    servicesLabel:     'Services & Pricing',
    bioLabel:          'About Us',
    highlightsLabel:   'Why Choose Us',
    contactLabel:      'Book an Appointment',
    contactVariant:    'both' as const,
    serviceCardAction: 'book' as const,
    orderLabel:        'Book',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
  doctor: {
    tabLabel:          'Appointments',
    heroCtaTarget:     '#book',
    servicesLabel:     'Consultations & Treatments',
    bioLabel:          'About Dr.',
    highlightsLabel:   'Our Approach',
    contactLabel:      'Book a Consultation',
    contactVariant:    'both' as const,
    serviceCardAction: 'book' as const,
    orderLabel:        'Book',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
  tutor: {
    tabLabel:          'Sessions',
    heroCtaTarget:     '#book',
    servicesLabel:     'Programs',
    bioLabel:          'Meet Your Tutor',
    highlightsLabel:   'Why Learn With Me',
    contactLabel:      'Book a Free Demo Class',
    contactVariant:    'both' as const,
    serviceCardAction: 'book' as const,
    orderLabel:        'Book Demo',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
  trainer: {
    tabLabel:          'Sessions',
    heroCtaTarget:     '#book',
    servicesLabel:     'Training Programs',
    bioLabel:          'My Journey',
    highlightsLabel:   'Why Train With Me',
    contactLabel:      'Book a Free Consultation',
    contactVariant:    'both' as const,
    serviceCardAction: 'book' as const,
    orderLabel:        'Enquire',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
  photographer: {
    tabLabel:          'Enquiries',
    heroCtaTarget:     '#portfolio',
    servicesLabel:     'Packages',
    bioLabel:          'My Story',
    highlightsLabel:   'My Style',
    contactLabel:      'Check My Availability',
    contactVariant:    'both' as const,
    serviceCardAction: 'book' as const,
    orderLabel:        'Enquire',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
  musician: {
    tabLabel:          'Enquiries',
    heroCtaTarget:     '#book',
    servicesLabel:     'I Perform At',
    bioLabel:          'About Me',
    highlightsLabel:   'Why Hire Me',
    contactLabel:      'Book Me for Your Event',
    contactVariant:    'both' as const,
    serviceCardAction: 'enquire' as const,
    orderLabel:        'Enquire',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
  other: {
    tabLabel:          'Inquiries',
    heroCtaTarget:     '#book',
    servicesLabel:     'What I Offer',
    bioLabel:          'About Me',
    highlightsLabel:   'Why Choose Me',
    contactLabel:      'Get in Touch',
    contactVariant:    'both' as const,
    serviceCardAction: 'none' as const,
    orderLabel:        'Get in Touch',
    hasQuantity:       false,
    hasNotes:          false,
    hasCustomOrder:    false,
    leadTimeNotice:    null,
  },
} as const

export type PersonaKey = keyof typeof PERSONA_CONFIG

export function getPersonaConfig(persona: string) {
  return PERSONA_CONFIG[(persona as PersonaKey)] ?? PERSONA_CONFIG.other
}
