-- Working Studio clinical data model for the physio persona.
-- Mirrors the advocate Drafting Studio stack at every layer:
--   draft_templates      → clinical_doc_templates
--   drafts               → clinical_notes + treatment_plans + hep_programs
--   clause_library       → exercise_library
--   drafting_usage       → working_usage
--
-- Patient roster reuses the generic students + student_sessions tables
-- (persona-relabeled "Patients / Sessions" in the UI via personaConfig.ts).
-- Clinical detail lives here, FK'd to students.id + providers.id.

-- ── 1. Clinical document templates ───────────────────────────────────────────
-- System templates (is_system=true, provider_id=null) are seeded in the
-- next migration. Members can also save their own custom templates.

CREATE TABLE IF NOT EXISTS clinical_doc_templates (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  doc_type     text        NOT NULL,            -- machine key: 'referral_letter', 'discharge_summary', etc.
  label        text        NOT NULL,            -- display name
  description  text,                            -- one-line summary
  fields       jsonb       NOT NULL DEFAULT '[]',  -- [{ id, label, placeholder, required }]
  body_scaffold text,                           -- optional HTML starting structure
  persona      text        NOT NULL DEFAULT 'physio',
  is_system    boolean     NOT NULL DEFAULT true,
  provider_id  uuid        REFERENCES providers(id) ON DELETE CASCADE,  -- null = system
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_clinical_templates_persona  ON clinical_doc_templates(persona, is_system);
CREATE INDEX IF NOT EXISTS idx_clinical_templates_provider ON clinical_doc_templates(provider_id) WHERE provider_id IS NOT NULL;

-- ── 2. Clinical notes ─────────────────────────────────────────────────────────
-- Stores initial evaluation notes (note_type='eval'), SOAP progress notes
-- (note_type='progress'), and discharge summaries (note_type='discharge').
-- body contains the full HTML document generated by the Working Studio editor.
-- body_chart is a jsonb canvas of pain markers: [{x, y, type, label, intensity}].

CREATE TABLE IF NOT EXISTS clinical_notes (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  provider_id  uuid        NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
  student_id   uuid                 REFERENCES students(id) ON DELETE SET NULL,
  note_type    text        NOT NULL DEFAULT 'progress' CHECK (note_type IN ('eval', 'progress', 'discharge')),
  visit_date   date        NOT NULL DEFAULT CURRENT_DATE,
  subjective   text        NOT NULL DEFAULT '',   -- raw bullet input (subjective section)
  objective    text        NOT NULL DEFAULT '',   -- raw bullet input (objective section)
  assessment   text        NOT NULL DEFAULT '',   -- raw bullet input (assessment section)
  plan         text        NOT NULL DEFAULT '',   -- raw bullet input (plan section)
  body         text        NOT NULL DEFAULT '',   -- full HTML note (editor output)
  body_chart   jsonb       NOT NULL DEFAULT '[]', -- pain markers on body diagram
  status       text        NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'final')),
  share_token  uuid        UNIQUE,               -- set to gen_random_uuid() to enable share link
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_clinical_notes_provider ON clinical_notes(provider_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_clinical_notes_student  ON clinical_notes(student_id) WHERE student_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_clinical_notes_token    ON clinical_notes(share_token) WHERE share_token IS NOT NULL;

-- ── 3. Treatment plans ────────────────────────────────────────────────────────
-- Stores physiotherapy treatment / care plans generated from assessment findings.
-- goals, modalities, phases are stored as jsonb so the AI can populate structured data
-- and the UI can render editable fields alongside the rich HTML document.

CREATE TABLE IF NOT EXISTS treatment_plans (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  provider_id     uuid        NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
  student_id      uuid                 REFERENCES students(id) ON DELETE SET NULL,
  title           text        NOT NULL,
  diagnosis       text        NOT NULL DEFAULT '',   -- working diagnosis / clinical impression
  goals           jsonb       NOT NULL DEFAULT '[]', -- [{type:'short'|'long', goal, target_date, achieved}]
  modalities      jsonb       NOT NULL DEFAULT '[]', -- [{name, frequency, notes}]
  frequency       text        NOT NULL DEFAULT '',   -- e.g. "2× per week for 6 weeks"
  duration_weeks  integer,
  phases          jsonb       NOT NULL DEFAULT '[]', -- [{phase, focus, criteria_for_progression}]
  body            text        NOT NULL DEFAULT '',   -- full HTML plan document
  status          text        NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'active', 'completed', 'on_hold')),
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_treatment_plans_provider ON treatment_plans(provider_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_treatment_plans_student  ON treatment_plans(student_id) WHERE student_id IS NOT NULL;

-- ── 4. Exercise library ────────────────────────────────────────────────────────
-- System exercises (is_system=true, provider_id=null) are seeded in the
-- next migration, grouped by body region / category.
-- Members can add their own exercises (is_system=false, provider_id set).
-- This is the physio analog of clause_library.

CREATE TABLE IF NOT EXISTS exercise_library (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  provider_id   uuid        REFERENCES providers(id) ON DELETE CASCADE,  -- null = system exercise
  persona       text        NOT NULL DEFAULT 'physio',
  category      text        NOT NULL,   -- body region: 'lumbar', 'cervical', 'shoulder', 'hip', 'knee', 'ankle', 'core', 'upper_limb', 'lower_limb', 'balance', 'breathing', 'general'
  name          text        NOT NULL,
  description   text        NOT NULL DEFAULT '',   -- brief clinical description of the exercise
  instructions  text        NOT NULL DEFAULT '',   -- patient-facing step-by-step cues (plain text)
  default_sets  integer     NOT NULL DEFAULT 3,
  default_reps  integer,     -- null if the exercise uses duration/hold rather than reps
  default_hold  integer,     -- seconds to hold (for isometric / static exercises)
  default_duration text,     -- e.g. "30 seconds", "2 minutes" (for cardio / timed exercises)
  media_url     text,        -- optional image or video URL
  is_system     boolean     NOT NULL DEFAULT true,
  tags          jsonb       NOT NULL DEFAULT '[]',
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_exercise_library_persona  ON exercise_library(persona, is_system);
CREATE INDEX IF NOT EXISTS idx_exercise_library_category ON exercise_library(category);
CREATE INDEX IF NOT EXISTS idx_exercise_library_provider ON exercise_library(provider_id) WHERE provider_id IS NOT NULL;

-- ── 5. Home exercise programs (HEP) ──────────────────────────────────────────
-- Stores assembled HEP handouts, including the structured exercises jsonb
-- (for re-editing) and the generated HTML handout (for printing/sharing).

CREATE TABLE IF NOT EXISTS hep_programs (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  provider_id  uuid        NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
  student_id   uuid                 REFERENCES students(id) ON DELETE SET NULL,
  title        text        NOT NULL,
  exercises    jsonb       NOT NULL DEFAULT '[]', -- [{exercise_id?, name, sets, reps, hold, duration, frequency, cues, image_url?}]
  instructions text        NOT NULL DEFAULT '',   -- general instructions / precautions
  body         text        NOT NULL DEFAULT '',   -- full HTML handout (editor output)
  status       text        NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'final')),
  share_token  uuid        UNIQUE,               -- shareable patient link
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_hep_programs_provider ON hep_programs(provider_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_hep_programs_student  ON hep_programs(student_id) WHERE student_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_hep_programs_token    ON hep_programs(share_token) WHERE share_token IS NOT NULL;

-- ── 6. Outcome measures ───────────────────────────────────────────────────────
-- Stores repeated outcome-measure recordings per patient, enabling trend tracking.
-- measure_type is the standardised tool name.
-- value stores raw input (e.g. scale items, individual ROM readings in degrees).
-- score stores the computed/normalised score (e.g. ODI % = 0-100).

CREATE TABLE IF NOT EXISTS outcome_measures (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  provider_id   uuid        NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
  student_id    uuid        NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  measure_type  text        NOT NULL,
  -- Types: VAS | NPRS | ROM_lumbar | ROM_cervical | ROM_shoulder | ROM_hip | ROM_knee | ROM_ankle
  --        MMT | ODI | NDI | DASH | LEFS | PSFS | TSK | FABQ | VISA_A | KOOS | HOOS
  --        Berg | TUG | 6MWT | other
  value         jsonb       NOT NULL DEFAULT '{}', -- raw input data {items, readings, etc.}
  score         numeric,                           -- computed normalised score
  unit          text,                              -- e.g. '°', '%', 'seconds', 'points'
  notes         text,                              -- clinical context for this recording
  recorded_date date        NOT NULL DEFAULT CURRENT_DATE,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_outcome_measures_patient  ON outcome_measures(student_id, recorded_date DESC);
CREATE INDEX IF NOT EXISTS idx_outcome_measures_provider ON outcome_measures(provider_id);
CREATE INDEX IF NOT EXISTS idx_outcome_measures_type     ON outcome_measures(student_id, measure_type, recorded_date DESC);

-- ── 7. Rate-limit counter ─────────────────────────────────────────────────────
-- Mirrors drafting_usage. WORKING_DAILY_LIMIT is enforced in the API route.

CREATE TABLE IF NOT EXISTS working_usage (
  provider_id  uuid        NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
  day_key      date        NOT NULL,
  count        integer     NOT NULL DEFAULT 0,
  PRIMARY KEY (provider_id, day_key)
);
